apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
    rhods/prebuilt: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/red-hat-data-services/s2i-generic-data-science-notebook"
    opendatahub.io/notebook-image-name: "Standard Data Science"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with a set of data science libraries that advanced AI/ML notebooks will use as a base image to provide a standard for libraries avialable in all notebooks"
    opendatahub.io/notebook-image-order: "20"
  name: s2i-generic-data-science-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8"}]'
      opendatahub.io/notebook-python-dependencies: '[{"name":"Boto3","version":"1.17"},{"name":"Kafka-Python","version":"2.0"},{"name":"Matplotlib","version":"3.4"},{"name":"Numpy","version":"1.19"},{"name":"Pandas","version":"1.2"},{"name":"Scikit-learn","version":"0.24"},{"name":"Scipy","version":"1.6"}]'
      openshift.io/imported-from: quay.io/modh/odh-generic-data-science-notebook
    from:
      kind: DockerImage
      # if you change the image tag, change the "-N" on the tag name immediately below
      name: quay.io/modh/odh-generic-data-science-notebook@sha256:3a8b19ea2ca3e8d04b0c858fe1d0aeb217eafe5cb4f6d2488e42b8c3b0cd3dde
    name: "py3.8-1"
    referencePolicy:
      type: Source
